# Generated by Django 3.0.2 on 2020-01-17 03:37

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('province', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contactName', models.CharField(max_length=120)),
                ('address', models.TextField()),
                ('emailAddress', models.EmailField(max_length=254)),
                ('phoneNumber', phone_field.models.PhoneField(max_length=31)),
            ],
        ),
    ]
